version: '3.8'
services: 
  database:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - my_data:/data/db 
  backend:
    container_name: node_api
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "3030:3030"
  frontend:
    container_name: js_react
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
volumes: 
  my_data: 